app.controller('MainController', ['$scope','$sce', function($scope, $sce){
//    $scope.jobTitle = 'Associate Product Manager';
//    $scope.dateTime = '8/18/2015 02:30PM';
//    $scope.company = 'Foursquare';
//    $scope.jobLocation = 'New York, NY';
//    $scope.jobType='Full-time';
//    $scope.jobLevel='Entry-level';
//    $scope.salary='50k-70k';
    $scope.jobs = [
        {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
        {jobTitle: 'Solutions Architect',
         dateTime: '8/18/2015 01:26PM',
         company: 'Amazon',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Mid-Level',
         salary: '120k-150k',
         description:$sce.trustAsHtml("<h4>Job Description:</h4><p>Are you passionate about helping startup companies use cloud computing to develop and deploy large scale applications? Do you have a unique combination of deep technical knowledge, business acumen and strong interpersonal skills? Amazon Web Services (AWS) is seeking a solutions architect to participate in startup-related activities such as architectural reviews and hackathons. The Solutions Architect will become a trusted advisor to our venture capital and startup customers, educating them on the value proposition of AWS and participating in deep architectural discussions to ensure their solutions are designed for successful deployment in the cloud.</p><p>Open to domestic travel up to 25%.</p><h4>Responsibilities:</h4><p>Help startup customers architect scalable, highly available application solutions that leverage AWS services</p><p>Work with AWS teams to drive startup-related revenue</p><p>Establish and build technical relationships within the startup ecosystem, including accelerators & incubators, VCs and co-working spaces in order to promote AWS</p><p>Develop technical content, such as white papers and reference architectures, that can be used by our customers to assist them in deploying cloud-based solutions</p><p>Represent AWS at startup-related industry events such as hackthons and Meetups</p><h4>Basic Qualifications:</h4><p>7+ years of experience in the design and implementation of complex IT systems</p><p>An understanding of application development and deployment concepts and tools including (source code management (Git, Subversion), continuous integration (Jenkins, Bamboo) Configuration management (Chef, Puppet)</p><p>An understanding of the cloud computing business model as it relates to startups</p><h4>Preferred Qualifications:</h4><p>An advanced degree in computer science, MIS, engineering or related discipline</p><p>Knowledge of multiple, modern development languages such as Ruby, Python and Node.js</p><p>Experience working for a venture-funded technology startup company</p><p>Experience in a customer-facing, sales-aligned role such as consultant, solutions engineer or solutions architect</p>")
        },
        {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
        {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
        {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
           {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
           {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
               {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        },
               {jobTitle: 'Associate Product Manager',
         dateTime: '8/18/2015 02:30PM',
         company: 'Foursquare',
         jobType: 'Full-time',
         jobLocation: 'New York, NY',
         jobLevel: 'Entry-level',
         salary: '50k-70k',
         description:$sce.trustAsHtml("<h4>About Foursquare:</h4><p>Foursquare helps you and your friends make the most of where you are. We're a small but highly ambitious company with millions of users worldwide relying on Foursquare to keep up with friends, discover what's nearby, save money and unlock deals. </p><p>To thrive as a member of Team Foursquare, you must embrace our exciting work-hard, play-hard environment. We're not afraid to move fast and break things as we release, launch, iterate, update and announce -- sometimes all in the same day. We're a closely-knit team and, especially at the end of a long day over beers, we feel like we're inventing the future together.</p><h4>Consumer Products at Foursquare:</h4><p>Foursquare’s mission is to help you make the most of where you are. The big question is how. Is it by being more social, with better ways to keep up with your friends? Or do we focus on motivation, getting people exploring more? What about fun; should we reward people for experiencing new things? As our next PM, you get to help us answer these questions and come up with new ways for people to discover what’s around them. </p><h4>Responsibilities:</h4><p>Understand and analyze user needs through user studies, market research, and data analysis Help define product vision and strategy, and build consensus among multiple teams like engineering, design, marketing, and business development.</p><p>Launch fast and iterate often with a team of the world-class engineers and designers Create and analyze metrics for products that you constantly use to evaluate success and come up with new product improvements</p><h4>Requirements:</h4><p>1-3 years experience in Product Management and / or Product Design developing Internet technologies BA/BS in Computer Science, Interaction Design, or a related field (technical experience is required; while you won’t be writing code you should understand the technical implications of the product decisions you make)Experience designing simple and intuitive web/mobile user interfaces; ability to create examples through wire frames and mock ups</p><p>Demonstrated experience planning and executing large-scale projects Strong analytical, organizational, and communication skills (verbal & written).  Passion for foursquare and location-based servicesBonus points for experience developing mobile, social, local and/or gaming technologies</p><p>To apply, send us your resume and a quick note about why you’re passionate about building consumer products at Foursquare.</p>")
        }
    
    ];
        
}]);

